name: "Infracost Core"
description: "Render current vs future cloud cost table and comment on PR"
author: faviaitsolutionab@gmail.com

branding:
  icon: cloud
  color: blue

inputs:
  working_dir:
    description: "Directory that contains tfplan.json for the PR plan"
    required: true
  base_tfplan_path:
    description: "Absolute path to baseline tfplan.json to compare against"
    required: true
  currency:
    description: "Currency code (e.g., SEK, USD, EUR)"
    required: false
    default: USD
  ping_author:
    description: "Mention PR author in the comment"
    required: false
    default: "true"
  mention_handles:
    description: "Space-separated or @-prefixed handles to mention"
    required: false
    default: ""
  infracost_version:
    description: "Infracost CLI version or 'latest'"
    required: false
    default: "latest"
  comment_marker:
    description: "Marker to deduplicate PR comments"
    required: false
    default: "<!-- infracost-comment -->"
  comment_title:
    description: "Markdown H3 title for the comment"
    required: false
    default: "💸 Infracost Report"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: "3.13"

    - name: Install Infracost
      shell: bash
      run: |
        set -euo pipefail
        if [ "${{ inputs.infracost_version }}" = "latest" ]; then
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
        else
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh -s -- -v "${{ inputs.infracost_version }}"
        fi
        infracost --version

    - name: Resolve paths
      id: paths
      shell: bash
      run: |
        set -euo pipefail
        WD="${{ inputs.working_dir }}"
        BASE="${{ inputs.base_tfplan_path }}"
        if [[ "$WD" != /* ]]; then WD="${GITHUB_WORKSPACE%/}/$WD"; fi
        if [[ ! -f "$WD/tfplan.json" ]]; then echo "PR tfplan.json not found at $WD/tfplan.json" >&2; exit 1; fi
        if [[ ! -f "$BASE" ]]; then echo "base_tfplan_path not found: $BASE" >&2; exit 1; fi
        echo "wd=$WD" >> "$GITHUB_OUTPUT"
        echo "base=$BASE" >> "$GITHUB_OUTPUT"

    - name: Build breakdowns and diff
      shell: bash
      env:
        INFRACOST_API_KEY: ${{ env.INFRACOST_API_KEY }}
        INFRACOST_CURRENCY: ${{ inputs.currency }}
      run: |
        set -euo pipefail
        WD='${{ steps.paths.outputs.wd }}'
        BASE='${{ steps.paths.outputs.base }}'
        infracost breakdown --path "$BASE" --format json --out-file "$WD/.infracost-base.json"
        infracost breakdown --path "$WD/tfplan.json" --format json --out-file "$WD/.infracost-pr.json"
        infracost diff --path "$WD/.infracost-pr.json" --compare-to "$WD/.infracost-base.json" --format json --out-file "$WD/infracost.out.json"

    - name: Generate PR comment markdown
      shell: bash
      env:
        PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        MENTION_HANDLES: ${{ inputs.mention_handles }}
        INPUT_COMMENT_MARKER: ${{ inputs.comment_marker }}
        INFRACOST_CURRENCY: ${{ inputs.currency }}
        INFRACOST_WD: ${{ steps.paths.outputs.wd }}
        PING_AUTHOR: ${{ inputs.ping_author }}
        PING_MENTIONS: ${{ inputs.ping_author }}
        COMMENT_TITLE: ${{ inputs.comment_title }}
      run: |
        set -euo pipefail
        WD='${{ steps.paths.outputs.wd }}'
        PY="${{ github.action_path }}/scripts/infracost_comment.py"
        python "$PY" "$WD/infracost.out.json" "$WD/infracost_comment.md"

    - name: Create/Update PR comment
      uses: actions/github-script@v7
      env:
        WD: ${{ steps.paths.outputs.wd }}
        MARKER: ${{ inputs.comment_marker }}
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const { owner, repo } = context.repo;
          const pr = context.payload.pull_request;
          if (!pr) return;
          const issue_number = pr.number;
          const body = fs.readFileSync(path.join(process.env.WD, 'infracost_comment.md'), 'utf8');
          const marker = process.env.MARKER || '<!-- infracost-comment -->';
          const { data: comments } = await github.rest.issues.listComments({ owner, repo, issue_number });
          const existing = comments.find(c => c.body && c.body.includes(marker));
          if (existing) {
            await github.rest.issues.updateComment({ owner, repo, comment_id: existing.id, body });
          } else {
            await github.rest.issues.createComment({ owner, repo, issue_number, body });
          }